# Display color
set -g default-terminal "tmux-256color"
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

# Mouse based copy
bind-key -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
bind-key -T copy-mode MouseDragEnd1Pane send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

# more history outputs
set -g history-limit 10000

bind -n C-s setw synchronize-panes
set -g renumber-windows on

set -as terminal-features "*:hyperlinks"
