[project]
name = "htoolbox"
version = "0.10.2"
description = "This package includes various tools for developers."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "json5>=0.13.0",
    "pip>=25.3",
    "pyyaml>=6.0.3",
    "rich>=14.2.0",
    "wget>=3.2",
]

[dependency-groups]
dev = [
    "ruff>=0.15.9",
]

[project.scripts]
tmuxer = "htoolbox.tmuxer.tmuxer:main"
vd = "htoolbox.downloader.vd:main"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
script-files = [
    "htoolbox/vscode/codeit",
    "htoolbox/hscan",
    "htoolbox/singularity/smagic",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["htoolbox*"]

[tool.uv]
default-groups = []

[tool.ruff.lint]
ignore = [
    "F401", # Ignore unused imports
    "F403", # Ignore 'from module import *' used
    "F841", # Ignore unused variables
]
