session: dev-session
window: workspace
num_panes: 3
layout: even-vertical
pane: 0
kill: true
commands:
  - pane_index: "0-1"
    commands:
      - bash
  - pane_index: "0"
    commands:
      - bash
      - cd <somedir>
  - pane_index: "1"
    commands:
      - cd /bin
  - pane_index: "2"
    commands:
      - htop
